tasks:
  build: pip3 install -r ./requirements.txt
  test: python3 -m py_compile bigode-pipelines.py
  compress: zip -r project.zip ./

pipelines:
  - name: build
    tasks:
      - build
  - name: release
    tasks:
    - build
    - test
    - compress
