version: 2
jobs:
  build:
    docker:
      - image:  python:3.6
    steps:
      - checkout
      - run: pip3 install -r ./requirements.txt
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: python3 -m py_compile bigode-pipelines.py
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - hold:
          type: approval
          requires:
           - build
      - test:
          requires:
            - hold
