version: 2
jobs:
  build:
    docker:
      - image:  python:3.6
    steps:
      - checkout
      - run: pip3 install -r ./requirements.txt
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: python3 -m py_compile bigode-pipelines.py
  deploy:
    docker:
      - image: python:3.6
    steps:
      - run: echo "Deploy"


workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - test
      - deploy:
          requires:
            - hold
